query Users($where: UserWhere) {
  users(where: $where) {
    email
    username
    OrganisedEventConnection {
      edges {
        node {
          slug
          title
          links {
            URL
            name
          }
          details
        }
      }
    }
    links {
      name
      URL
    }
  }
}
