mutation Mutation($input: [EventCreateInput!]!) {
  createEvents(input: $input) {
    events {
      id
      title
      toDate
      organisers {
        email
        username
      }
      details
    }
  }
}